matrix:
  include:
    - language: go
      go: "1.10"
      before_install:
        - cd cli/
        - go get -u github.com/golang/dep/cmd/dep
        - dep ensure
      script:
        - go test -v ./...
    - language: java
      before_install:
        - apt-get update -qq
        - apt-get -qq install -y software-properties-common
        - add-apt-repository -y ppa:maarten-fonville/protobuf
        - apt-get update -qq
        - apt-get install -y protobuf-compiler
      script:
        - mvn test
